"""Add backend_metrics to database

Revision ID: 8bd4627f0cf9
Revises: 054789972051
Create Date: 2026-04-01 20:37:06.618261

"""
from alembic import op
import sqlalchemy as sa
import server as database

# revision identifiers, used by Alembic.
revision = '8bd4627f0cf9'
down_revision = '054789972051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backend_metrics',
    sa.Column('network', database.NetworkTypeValue(), nullable=False),
    sa.Column('loop_counter', sa.Integer(), nullable=False),
    sa.Column('total_users_processed', sa.Integer(), nullable=False),
    sa.Column('total_loop_time', sa.Float(), nullable=False),
    sa.Column('last_loop_start_time', sa.Float(), nullable=False),
    sa.Column('last_loop_end_time', sa.Float(), nullable=False),
    sa.Column('current_loop_queue', sa.Integer(), nullable=False),
    sa.Column('last_loop_queue', sa.Integer(), nullable=False),
    sa.Column('backend_start_time', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('network')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backend_metrics')
    # ### end Alembic commands ###
