"""Add backend_metrics to database

Revision ID: 8bd4627f0cf9
Revises: 054789972051
Create Date: 2026-04-01 20:37:06.618261

"""
from alembic import op
import sqlalchemy as sa
import server as database

# revision identifiers, used by Alembic.
revision = '8bd4627f0cf9'
down_revision = '054789972051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backend_metrics',
    sa.Column('network', database.NetworkTypeValue(), nullable=False),
    sa.Column('loop_counter', sa.Integer(), nullable=False),
    sa.Column('total_users_processed', sa.Integer(), nullable=False),
    sa.Column('total_loop_time', sa.Float(), nullable=False),
    sa.Column('last_loop_start_time', sa.Float(), nullable=False),
    sa.Column('last_loop_end_time', sa.Float(), nullable=False),
    sa.Column('current_loop_queue', sa.Integer(), nullable=False),
    sa.Column('last_loop_queue', sa.Integer(), nullable=False),
    sa.Column('backend_start_time', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('network')
    )
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.drop_column('last_check')

    with op.batch_alter_table('friends', schema=None) as batch_op:
        batch_op.drop_column('last_update_status')
        batch_op.drop_column('last_updated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friends', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.BIGINT(), nullable=True))
        batch_op.add_column(sa.Column('last_update_status', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_check', sa.BIGINT(), nullable=True))

    op.drop_table('backend_metrics')
    # ### end Alembic commands ###
